### PR TITLE
Add read concern for mongo driver 3.4

### PR DESCRIPTION
**Pull request by karimad**

### CODE REVIEW

**Comment by karimad** [comment]
can anyone please review this pr ? thanks

**Comment by bguerout** [comment]
Hello thanks for your pull request.
I can quickly review it on my smartphone but haven't access to a desktop untill the next week.

**Comment by bguerout** [comment]
Hello, I'm going check this locally (+regression tests `https://github.com/bguerout/jongo/tree/master/src/test/sh`) but it sounds good to me

**Comment by karimad** [comment]
thanks !

**Comment by karimad** [comment]
hello any updates ?

**Comment by bguerout** [comment]
Thanks again.
I'm going to update minimal mongo java driver to 3.4.0

**Pull request merged**
